[package]
name = "gol.rs"
version = "0.0.1"
authors = ["Peter Jacobs <peter@crespyl.net>"]

[[bin]]
name = "gol"
path = "src/gol.rs"

[dependencies]
rand = "*"
bitflags = "*"
rustc-serialize = "*"

docopt = "*"
docopt_macros = "*"
