[package]
name = "ca.rs"
version = "0.0.1"
authors = ["Peter Jacobs <peter@crespyl.net>"]

[[bin]]
name = "ca"
path = "src/ca.rs"

[dependencies]
rand = "*"
bitflags = "*"
rustc-serialize = "*"

docopt = "*"
docopt_macros = "*"
